### ISSUE TITLE
This looks great!

### ISSUE THREAD

**Issue by syrusakbary** [helmutkian/cl-wasm-runtime#1]
Hey @helmutkian, I just discovered this package for running Wasm in Lisp through Wasmer and I think it's awesome!

I'm Syrus, from the Wasmer team. I was wondering if you would like us to link your project from the Wasmer repo, so other people can also discover it easily!

Let me know :)

**Comment by helmutkian** [comment]
Hey there @syrusakbary, thanks for the kind words!

This package is still under heavy development. While it's functioning, there's still some interface and stability concerns that need to be addressed--not to mention needing documentation.

I very much appreciate the offer to link from the Wasmer repo. I would just recommend a disclaimer that the project is still unfinished. I was going to wait until there was at least some basic documentation in place before exposing this project further, but as long as users are aware this isn't something ready for prod, I don't see the harm in inviting some extra eyeballs and potentially more contributors.

**Comment by syrusakbary** [comment]
I added it to the Wasmer repo with a small disclaimer.

We can close this issue now. Let me reinforce your great work on the package!
